### ISSUE TITLE
Create a command line interface for Winch.

### ISSUE THREAD

**Issue by tylercritchlow** [Winch-Team/winch#3]
### Description

We need a simple to use CLI that allows users to interact with Winch after installing.

### Checklist

- [x] Possibly create our own crate for parsing CLI args
- [ ] Installing and uninstalling commands
- [ ] Custom user hosted repo handling (`--index=`)

**Comment by brodycritchlow** [comment]
Been looking at this crate, [BPAF](https://docs.rs/bpaf/latest/bpaf/) seems more straight to the point than Clap.

**Comment by brodycritchlow** [comment]
Completed in production release 1.
